console.log('this 11ge112311');
/**
 * {
    id: 'page2',
    ids: [ 'page2' ],
    debugId: 1002,
    name: 'page2',
    preventIntegration: false,
    entryModule: NormalModule {
      dependencies: [],
      blocks: [],
      variables: [],
      type: 'javascript/auto',
      context: '/Users/hanxf.han/project/webpack-all-config-demo/6.plugin-principle/src',
      debugId: 1001,
      hash: '0c7040d177d11058339fe398d029c046',
      renderedHash: '0c7040d177d11058339f',
      resolveOptions: {},
      factoryMeta: {},
      warnings: [],
      errors: [],
      buildMeta: [Object],
      buildInfo: [Object],
      reasons: [Array],
      _chunks: [SortableSet [Set]],
      id: './src/page2.js',
      index: 4,
      index2: 4,
      depth: 0,
      issuer: null,
      profile: undefined,
      prefetched: false,
      built: true,
      used: null,
      usedExports: null,
      optimizationBailout: [],
      _rewriteChunkInReasons: undefined,
      useSourceMap: false,
      _source: [OriginalSource],
      request: '/Users/hanxf.han/project/webpack-all-config-demo/6.plugin-principle/src/page2.js',
      userRequest: '/Users/hanxf.han/project/webpack-all-config-demo/6.plugin-principle/src/page2.js',
      rawRequest: './src/page2.js',
      binary: false,
      parser: [Parser],
      generator: JavascriptGenerator {},
      resource: '/Users/hanxf.han/project/webpack-all-config-demo/6.plugin-principle/src/page2.js',
      matchResource: undefined,
      loaders: [],
      error: null,
      _sourceSize: null,
      _buildHash: '4705f59b6d24369f2712949672473ac7',
      buildTimestamp: 1601367698593,
      _cachedSources: Map {},
      lineToLine: false,
      _lastSuccessfulBuildMeta: [Object],
      _ast: null
    },
    _modules: SortableSet [Set] {
      [NormalModule],
      _sortFn: [Function: sortByIdentifier],
      _lastActiveSortFn: null,
      _cache: undefined,
      _cacheOrderIndependent: undefined
    },
    filenameTemplate: undefined,
    _groups: SortableSet [Set] {
      [Entrypoint],
      _sortFn: [Function: sortChunkGroupById],
      _lastActiveSortFn: null,
      _cache: undefined,
      _cacheOrderIndependent: undefined
    },
    files: [],
    rendered: false,
    hash: 'e6d8c304bf6c07033896ae727beb8328',
    contentHash: [Object: null prototype] { javascript: 'e289b140fc78bb6123f6' },
    renderedHash: 'e6d8c304bf6c07033896',
    chunkReason: undefined,
    extraAsync: false,
    removedModules: undefined
  }
 */